### ISSUE TITLE
Improve Mozilla VR team tagline/mission/motto

### ISSUE THREAD

**Issue by cvan** [MozVR/mozvr-site#151]
And, even though we changed the name on [our Blog](https://blog.mozvr.com), Twitter, and a few other places, the `<title>` of [our domain name](https://mozvr.com/), the `MozVR` wordmarks on the site, etc. continue to confuse folks in the Web + VR communities, press, community, and even some internal Mozilla folks I've heard are confused about the term `MozVR`.

This is our current tagline that appears in our [site](https://mozvr.com/) (and our [`@MozillaVR` Twitter account](https://twitter.com/mozillavr)):

`We are the Mozilla VR team. Our goal is to help bring high-performance virtual reality to the open Web.`

Our mission statement/team motto should be more succinct (and clearer to non-VR enthusiasts):

`Bringing Virtual Reality browsing and enabling ecosystem to the Web.`

Or, paraphrased from a blog post:

`The Mozilla VR team supports the online creation and display of VR content in the browser.`

But, it could be shorter and more descriptive.

Let's also be consistent with the usage everywhere (e.g., our [`@MozillaVR` Twitter account](https://twitter.com/mozillavr)).

**Comment by caseyyee** [comment]
`To define and evolve the Web as a platform for immersive VR experiences.`

That's what it says in our plan.  What do you think?     I think _browser_ is a little too specific?

**Comment by cvan** [comment]
In that context, platform, immersive, and experiences are too vague of words to mean nothing to pretty much anyone.

I continue to see people read our copy, mission statement and say MozVR is an application or a VR browswer or a community.

Let's try to use words that non-VR folks can recognize (lots of press and potential partners come to this site, for example).

**Comment by ngokevin** [comment]
Funny thing, for some people, the name change from MozVR -> Mozilla VR hasn't differentiated it as a product vs. a team. "How do I install Mozilla VR?"..."I was trying to get it working with Mozilla VR". I don't have any suggestions on the motto yet, just chiming in with that nugget.

**Comment by darkwing** [comment]
Some ideas to throw into the pot:

- [ ] - "Standardizing VR on the Web" - Super simple, doesn't overcomplicate, but not engaging
- [ ] - "Standardizing and creating VR on the Web" - Again, think "Standardizing" could be too robotic
- [ ] - "Bringing virtual reality experiences to the web" - Short, sweet, exciting
- [ ] - "Bringing virtual reality standards and experiences to the web" - Adding "standards" to include the Mozilla mission

Keywords to think about: 

- [ ] - "immersive" - Not sure everyone understands that
- [ ] - "experiences" - Vague word...can't decide if that's good or bad.
