### ISSUE TITLE
Add Daosheng to Team

### ISSUE THREAD

**Issue by cvan** [MozVR/mozvr-site#169]

**Comment by cvan** [comment]
@daoshengmu do you have a picture you'd like use on https://mozvr.com/#team?

**Comment by daoshengmu** [comment]
Sure. I choose this one. Thanks.
![1463252_10200936070440751_5421550496356853515_n](https://cloud.githubusercontent.com/assets/1263177/20738902/90f97484-b6f1-11e6-8901-df03f9cf8022.jpg)
