### ISSUE TITLE
Consider importing issues from MozVR/MozVR.com-issues

### ISSUE THREAD

**Issue by cvan** [MozVR/mozvr-site#2]
Now that this repo is public, perhaps [MozVR/MozVR.com-issues](https://github.com/MozVR/MozVR.com-issues) can be closed - and its [issues](https://github.com/MozVR/MozVR.com-issues/issues) be imported here?

**Comment by caseyyee** [comment]
I was thinking that this would be a good idea.   Not sure how to do this though.  Will look into it!

**Comment by jcarpenter** [comment]
Yeah agreed. Makes sense :)

**Comment by jcarpenter** [comment]
Why don't we just close that repo? The issues inside pertain to the old version of the site (the original Hiro demo) and are no longer applicable to the new site...

**Comment by cvan** [comment]
https://github.com/MozVR/MozVR.com-issues is closed
