### ISSUE TITLE
Force HTTPS

### ISSUE THREAD

**Issue by cvan** [MozVR/mozvr-site#53]
Dependent on #45 because we can't have mixed content with the Polar Sea video.

**Comment by caseyyee** [comment]
We should just get rid of this demo and find something else IMO.

**Comment by cvan** [comment]
I'm down

**Comment by cvan** [comment]
Filed bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1263780

**Comment by cvan** [comment]
done!
