### ISSUE TITLE
Add custom analytics events for entering VR (and HMD state)

### ISSUE THREAD

**Issue by cvan** [MozVR/mozvr-site#66]

**Comment by caseyyee** [comment]
Hmm.   We would have to instrument the individual demo's since users click directly into the demos themselves.   I think https://github.com/MozVR/mozvr.com/commit/fdae0df7eb2f358f670987020a6b19477e065fb2 covers most of what we need?

**Comment by cvan** [comment]
yeah, we just have to add the selectors for the "enter VR" buttons. pretty trivial after that patch of mine we merged.
