### ISSUE TITLE
"Enter VR" button for Sechelt should be above the fold

### ISSUE THREAD

**Issue by cvan** [MozVR/mozvr-site#78]
Often times it's below the fold, so I/folks miss it

**Comment by caseyyee** [comment]
what do you think about having it just under the headline text?   that way its a little more central/easy to see.

**Comment by cvan** [comment]
perhaps, would have to see it. idk, I'm rather not have the masthead be so huge anyway.

**Comment by cvan** [comment]
removing Sechelt (#149).
