### ISSUE TITLE
Showcase Secvrity from boondogl

### ISSUE THREAD

**Issue by caseyyee** [MozVR/mozvr-site#92]
Unity exported WebVR example

**Comment by cvan** [comment]
https://s3-us-west-1.amazonaws.com/boondogl-games/SECVRITY/
http://www.boondogl.com/

do you have to be logged in to play it?

**Comment by caseyyee** [comment]
I have the standalone files that we'll host.   Just asking them for some updates first.

**Comment by cvan** [comment]
done
