### ISSUE TITLE
add Fernando to Team list

### ISSUE THREAD

**Issue by cvan** [MozVR/mozvr-site#98]
http://mozvr.com/#team

@fernandojsg can you send me a high-res pic of yourself?

**Comment by fernandojsg** [comment]
Yep, I'll find one and I'll send you

**Comment by cvan** [comment]
@fernandojsg ping

**Comment by fernandojsg** [comment]
Just sent you an email!

**Comment by cvan** [comment]
![fserrano](https://cloud.githubusercontent.com/assets/203725/16766071/98d3708e-47ec-11e6-817c-4d5fdfba80a9.jpg)
